### PR TITLE
Show broken HashSet

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks! Now I have to fix this ;)

**Comment by forki** [comment]
Will add some more. for remove and stuff ;-)

**Comment by alfonsogarciacaro** [comment]
I think remove is already being tested as it also returns true/false in JS. Not sure which other methods have return values different from .NET though.

**Comment by forki** [comment]
yes just saw that. lol

**Pull request merged**
