### PR TITLE
Add Fable.Import.Test.fsproj to build

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
all the errors are unrelated and already there. what do we do?

**Comment by alfonsogarciacaro** [comment]
That's because this breaking change: #279. Let me finish v0.5.0, update the bindings and the samples and then we can merge the PR :+1:

**Comment by forki** [comment]
cool. just let me know if I have to do something.

**Comment by alfonsogarciacaro** [comment]
New version is about to be released, so let's start fixing these things :+1:

**Pull request merged**
