### PR TITLE
Add flexible type overload for React.createElement

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Makes stuff much cleaner.

### CODE REVIEW

**Comment by forki** [comment]
"Makes stuff much cleaner." TM

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by forki** [comment]
is this already released?

**Comment by alfonsogarciacaro** [comment]
Now it is 😉 `fable-import-react@0.1.1`

**Comment by forki** [comment]
:kiss:

**Pull request merged**
