### PR TITLE
fix link to the directory of curated definitions

### PR DESCRIPTION
**Pull request by scitesy**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Thanks!

**Comment by scitesy** [comment]
You are welcome! I'll get the rest of them soon. Hopefully in one PR;)

**Comment by alfonsogarciacaro** [comment]
I've to do a big update of the docs this weekend so I'd wait a bit to avoid stepping on each other's toes :)

**Comment by scitesy** [comment]
Good to know. Thanks.

**Pull request merged**
