### PR TITLE
Add ReactNative helper

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by forki** [comment]
@alfonsogarciacaro could you please release this? Would love to test it from package

**Comment by alfonsogarciacaro** [comment]
Done! :+1:

**Comment by forki** [comment]
here is a sample: https://github.com/Krzysztof-Cieslak/fable-react_native-demo/blob/master/src/ImagePickerApp.fs#L28

**Comment by alfonsogarciacaro** [comment]
This looks really useful! I'll try to add more helpers for the other components :+1:

**Comment by forki** [comment]
that would be awesome.

**Comment by forki** [comment]
meanwhile I'm trying to do the actual prototype ;-)

**Pull request merged**
