### PR TITLE
WIP: adds --declaration compiler option to generate TypeScript declaration files (.d.ts)

### PR DESCRIPTION
**Pull request by fdcastel**
Discussion at #270 

VERY EARLY implementation. Just the bare minimum to compile current `integration-typescript` sample.

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
I just merged a PR with many changes, could you please rebase with master to avoid dealing with many conflicts later? Thanks! :+1:

**Comment by fdcastel** [comment]
Sure! I'll do it in the next few hours. :+1:

**Comment by fdcastel** [comment]
Done! However, I believe a new release of `fable-core` is in order.

Currently both integration samples are failing with:

```
ERROR: C:\Temp\Fable\samples\node\integration-babel\out\util.js:13
    }, s.reverse()));
         ^

TypeError: s.reverse is not a function
```

**Comment by alfonsogarciacaro** [comment]
Sorry but, as commented on #270, I've been exploring another way that looks more promising. I've sent a WIP PR (#308), maybe we could close this one and work together on the other?

**Comment by fdcastel** [comment]
Sure! Let's continue this with #308! :+1: :wink:

**Pull request closed without merging**
